M48
; DRILL file {KiCad 6.0.0-rc1-unknown-fbdb2bd91f~144~ubuntu20.04.1} date Rab 08 Des 2021 11:49:30 
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-12-08T11:49:30+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0-rc1-unknown-fbdb2bd91f~144~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X6.6241Y-3.8702
X6.7422Y-3.8702
T0
M30
